from .base_scene import BaseScene
from .formulas import (
    # Scene 4 — Localization
    FORMULA_DAUGMAN,
    FORMULA_LOCALIZATION,
    # Scene 5 — Normalization
    FORMULA_NORMALIZATION,
    FORMULA_RUBBER_SHEET_OVERVIEW,
    FORMULA_RUBBER_SHEET_X,
    FORMULA_RUBBER_SHEET_Y,
    FORMULA_POLAR_RANGE,
    # Scene 6 — Feature Extraction
    FORMULA_FEATURE_EXTRACTION,
    FORMULA_GABOR_GAUSS,
    FORMULA_GABOR_SIN,
    # Scene 7 — Encoding
    FORMULA_COMPLEX_RE,
    FORMULA_COMPLEX_IM,
    FORMULA_COMPLEX_Z,
    FORMULA_DAUGMAN_ENCODING,
    FORMULA_BIT_RULES,
    FORMULA_IRIS_CODE,
    # Scene 8 — Matching
    FORMULA_MATCHING,
    FORMULA_HD_NUMERATOR,
    FORMULA_HD_DENOMINATOR,
    FORMULA_HD_NORM,
)

__all__ = [
    "BaseScene",
    # Formulas — Scene 4
    "FORMULA_DAUGMAN",
    "FORMULA_LOCALIZATION",
    # Formulas — Scene 5
    "FORMULA_NORMALIZATION",
    "FORMULA_RUBBER_SHEET_OVERVIEW",
    "FORMULA_RUBBER_SHEET_X",
    "FORMULA_RUBBER_SHEET_Y",
    "FORMULA_POLAR_RANGE",
    # Formulas — Scene 6
    "FORMULA_FEATURE_EXTRACTION",
    "FORMULA_GABOR_GAUSS",
    "FORMULA_GABOR_SIN",
    # Formulas — Scene 7
    "FORMULA_COMPLEX_RE",
    "FORMULA_COMPLEX_IM",
    "FORMULA_COMPLEX_Z",
    "FORMULA_DAUGMAN_ENCODING",
    "FORMULA_BIT_RULES",
    "FORMULA_IRIS_CODE",
    # Formulas — Scene 8
    "FORMULA_MATCHING",
    "FORMULA_HD_NUMERATOR",
    "FORMULA_HD_DENOMINATOR",
    "FORMULA_HD_NORM",
]
